site_name: BitBuilder Documentation
site_url: https://docs.vexelabs.io/bitbuilder
site_author: vexelabs contributors

# Repository Config
repo_name: vexelabs/bitbuilder
repo_url: https://github.com/vexelabs/bitbuilder
edit_uri: edit/master/docs/

theme:
  name: material
  favicon: static/vexelabs512x512.png
  icon:
    logo: material/memory

extra_css:
  - stylesheets/theme.css

# S3 redirects are bothersome without this disabled
use_directory_urls: false

nav:
  - Overview: index.md
  - Getting Started:
    - Downloads: downloads.md
    - Supported Platforms: supported-platforms.md
  - Core Concepts:
    - Type Casting and RTTI: casting-between-types.md
  - Advanced Recipes:
    - Custom LLVM Binaries: custom-llvm-binaries.md