name: Dokka Deploy
on:
  push:
    branches:
      - 'master'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: x86
      - name: Build Documentation
        run: |
          chmod +x ./gradlew
          ./gradlew build dokkaHtml
      - uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: dokka-autodeploy
          FOLDER: build/dokka