name: Dokka Deploy
on:
  push:
    branches:
      - 'master'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Documentation
        run: |
          java -version
          chmod +x ./gradlew
          ./gradlew build dokkaHtml
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
      - uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: dokka-autodeploy
          FOLDER: build/dokka