name: Test Suite
on: [push, pull_request]
jobs:
  run:
    name: Execute Test Suite
    strategy:
      matrix:
        operating-system: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          java -version
          chmod +x ./gradlew
          ./gradlew clean build test --refresh-dependencies
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false