name: CI Automation
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Style-check codebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Cache dependencies per commit hash because Sonatype OSS repo might
      # miss certain artifacts at times.
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: mvn-hash-cce3d80711f15665cf1058b40cc3587c19ec9d76
      # Install dependencies if git hash has changed
      - name: Install Maven Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: bash ./mvnw -f .dependencies/dependencies.pom.xml -U compile
      # Build and run lint check
      - run: bash ./gradlew clean build ktlintCheck --refresh-dependencies

  test:
    needs: [lint]
    name: Execute test suite
    strategy:
      matrix:
        operating-system: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
      # Cache dependencies per commit hash because Sonatype OSS repo might
      # miss certain artifacts at times.
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: mvn-hash-cce3d80711f15665cf1058b40cc3587c19ec9d76
      # Install dependencies if git hash has changed
      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: bash ./mvnw -f .dependencies/dependencies.pom.xml -U compile
      # Log system information and run tests
      - run: |
          bash --version
          bash ./gradlew --version
          java -version
      - run: bash ./gradlew clean build test --refresh-dependencies