name: Test Suite
on: [push, pull_request]
jobs:
  run:
    name: Execute Test Suite
    strategy:
      matrix:
        architecture: [x64, x86]
        operating-system: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: ${{ matrix.architecture }}
      - name: Run Tests
        run: |
          gradle clean build test --refresh-dependencies --debug --scan --stacktrace
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false