name: CI Automation
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  GRADLE_OPTS: -Dorg.gradle.caching=true
jobs:
  lint:
    name: Style-check codebase
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          mvn -f .dependencies/dependencies.pom.xml -U compile
          bash ./gradlew clean build --refresh-dependencies

      - uses: actions/checkout@v2
      - name: Run ktlint
        run: bash ./gradlew ktlintCheck

  test:
    name: Execute test suite
    strategy:
      matrix:
        operating-system: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Install Dependencies
        run: |
          mvn -f .dependencies/dependencies.pom.xml -U compile
          bash ./gradlew clean build --refresh-dependencies

      - uses: actions/checkout@v2
      - name: Log system information
        run: |
          bash --version
          bash ./gradlew --verion
          java -version

      - name: Execute kotlin test suite
        run: bash ./gradlew test

  samples:
    needs: [test]
    name: Ensure sample projects run
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          mvn -f .dependencies/dependencies.pom.xml -U compile
          bash ./gradlew clean build --refresh-dependencies

      - uses: actions/checkout@v2

      - name: FactorialJIT Example
        run: bash samples/run.sh factorial-jit